spring:
  application:
    name: eureka-server
###服务端口号
server:
  port: 8200
###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: eureka-peer2
    prefer-ip-address: false
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，如果要迅速获取服务注册状态，可以缩小该值
    lease-renewal-interval-in-seconds: 20
    ##元数据
    metadata-map:
      instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      ###分别配置对方的地址作为Eureka Client进行相互注册
      defaultZone: http://eureka-peer1:8100/eureka/,http://eureka-peer2:8200/eureka/,http://eureka-peer3:8300/eureka/
    register-with-eureka: true
    fetch-registry: true
